language: minimal
sudo: false

addons:
  apt:
    packages:
    - wget
    - libgmp-dev

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
  - futhark pkg sync

script:
  - futhark test --notty lib
  - futhark pkg upgrade
  - futhark pkg sync
  - futhark test --notty --pass-compiler-option=--Werror lib
